git add -A db
git add -A node_modules
git add -A public
git add -A routes
git add -A views
git add -A .idea
git add -A push.bat
git add -A pull.bat
git add -A git.txt
git add -A app.js
git add -A add.bat